### ISSUE TITLE
When using the new voting methods, sometimes the item given is a soldier's syringe instead of the selected item

### ISSUE THREAD

**Issue by Hamudrel** [JustDerb/RoR2-VsTwitch#26]
Found this a few days ago after updating. Meant to let you know but forgot.

Here it happened with orange items:
![OrangeItemBug](https://user-images.githubusercontent.com/76544259/107603493-8aced300-6bf2-11eb-947b-891c3c717ac6.PNG)

Then here is where it happened with a white drop and didn't with a green drop. Not sure if that's a good clue or not:
![WhiteGreenBug](https://user-images.githubusercontent.com/76544259/107603610-ec8f3d00-6bf2-11eb-9a6a-a883f61245b6.PNG)

These two were with Percentile, but it also happened with MaxVoteRandomTie.

Thanks and I love your mod!

**Comment by JustDerb** [comment]
Dang, this bug just keeps on coming back! I have about 2 spots that should stop stuff like this happening; seems like it still didn't protect against it.

Did restarting the run (not the game) fix it? Did restarting the game fix it?

**Comment by Hamudrel** [comment]
I haven't checked yet, I'll let you know. I just switched back to the MaxVote rating.

**Comment by JustDerb** [comment]
I updated the library and fixed a couple bugs around the voting parts of this game (in terms of the various strategies). I'm going to close this issue out as it probably has been fixed in the 1.0.9 update. If this isn't the case, feel free to reopen!
