### ISSUE TITLE
Doesnt Load Channel Point Events

### ISSUE THREAD

**Issue by DoctorLovely** [JustDerb/RoR2-VsTwitch#27]
Hey i dont know going but when i launch in the cmd box i get warning for every channel point event that it is unable to load [Warning: Unity Log] Could not register Channel Points event: Ally Beetle
And i cant seem to find how to fix
![log](https://user-images.githubusercontent.com/41946248/113470036-76ec6400-9420-11eb-9e4e-d7694cf5e4fb.PNG)

**Comment by DoctorLovely** [comment]
ok i solved the issue for anyone else having this problem. You have to put true/false on every single event to get them to load right. That first true false is weather you want them to be able to be used.

**Comment by JustDerb** [comment]
Note that you should follow the [section in the README.md](https://github.com/JustDerb/RoR2-VsTwitch/blob/main/README.md#channelpoints) to configure this. Passing `true`/`false` will **NOT** make this feature work correctly!
