### ISSUE TITLE
No votes default to first item in list (MaxVoteRandomTie)

### ISSUE THREAD

**Issue by HiroLeWeeb** [JustDerb/RoR2-VsTwitch#29]
When testing the mod to see if it worked properly, I noticed that if there was no vote for a chest item, it would default the dropped item to be the first one in list.

Pretty niche bug, but still worth mentioning in my opinion.

**Comment by JustDerb** [comment]
This is actually intended behaviour! The first item in the list (using the default vote strategy - `MaxVote`) is the item that the game would have dropped if the mod wasn't enabled.

If you are looking for it to randomly give you an item for no votes, you should switch to the `MaxVoteRandomTie` or `Percentile` vote strategies.

**Comment by HiroLeWeeb** [comment]
Thanks for the quick answer, but the issue is that I already changed value to MaxVoteRandomTie.
Just opened a multishop and it popped up as if I opened a normal chest.
Streaming right now (hiroleweeb) if you wanna see by yourself.
Also here's my profile code if it's remotely useful : ZetJRyQF01

**Comment by HiroLeWeeb** [comment]
https://clips.twitch.tv/RelentlessFancyRatPJSalt-OjZps2iHKzTJCs_G at 0:17

**Comment by JustDerb** [comment]
Ah, I didn't realize you switched the voting strategy. That would be a bug in that strategy.
