### ISSUE TITLE
"Percentile" gives broken items

### ISSUE THREAD

**Issue by ZeKwev** [JustDerb/RoR2-VsTwitch#30]
Hello,

When using the mod, the "Percentile" strategy doesn't work if there is more than one vote. The game gives a "Item AACANNON_NAME" item that does nothing and seems broken. 

What I tried (with VsTwitch as my only active mod)  : 
- Using the mod alone, offline, with Percentile. When I'm the only one voting, it picks the right item. 👍 
- Using the mod alone, offline, with Percentile. When I vote with two different Twitch account in the chat, the item is bugged. 👎 
- Using the mod online on stream, with Percentile. When people votes, the item is bugged. 👎 

The other methods (Max Votes) does work.

You can see it in this clip : https://clips.twitch.tv/CreativeSuspiciousLlamaFailFish-JXIvtFU8UF8Nlblq

![2021-08-26 05_02_03-Window](https://user-images.githubusercontent.com/89562439/130893647-e848526b-106c-4edd-b494-b2801dc586e5.png)

**Comment by JustDerb** [comment]
So I believe `ITEM_AACANNON_NAME` is the "first" Pickup in the game. Since there was a bug in my code, you'd get that.
