### ISSUE TITLE
VsTwitch interaction with ShareSuite

### ISSUE THREAD

**Issue by hrafnbrand** [JustDerb/RoR2-VsTwitch#37]
A simple question. I want to use VsTwitch on stream with friends, while also using ShareSuite (so we're not arguing about drop distribution). Before I get them together and set up a stream just to test, I thought I would ask here and possibly save the trouble. What sort of interactions can I expect from a combo of these two mods?

**Comment by JustDerb** [comment]
The way VsTwitch is created, ShareSuit doesn't affect the drops (if item voting is turned on). When playing multiplayer, with voting items on, all players receive the voted on item. So, for example, if you have 3 players and chat votes for a Bison Steak, all 3 players will receive a Bison Steak in their inventory.
