### ISSUE TITLE
A Way To Prevent Spamming My Twitch Chat

### ISSUE THREAD

**Issue by Collanaro** [JustDerb/RoR2-VsTwitch#38]
Loving this mod!  Tried it out on my channel today.  It makes the game like 100% more fun for the streamers and the viewers!  So cool!
  If I could make one suggestion, a way to disable it printing things like item voting and item voting results to chat would be nice.  I don't want to miss actual viewers talking to me.  We can all see what's happening on screen anyway.

**Comment by JustDerb** [comment]
Glad you like the mod! The text being sent in the chat is more for providing real-time feedback to viewers who might be on a large video delay for your stream. Sometimes a viewer might be as much as 10 seconds behind. Text chat is almost instantaneous, so it can provide good feedback to the viewer before they see it on screen.

But, I can add this as an option to disable this in the next version as I don't see this being super hard to implement. Do note that some viewers with higher delays might miss voting on items (especially if you have the voting period very low).
