### ISSUE TITLE
Chests Not Spawning Anything

### ISSUE THREAD

**Issue by DragonsMage1** [JustDerb/RoR2-VsTwitch#50]
Everything except the multistops are taking the money but then not dropping anything and not giving a choice to twitch, is there something that is messed up on my end?

**Comment by JustDerb** [comment]
Was there an error messages that popped up in the Console window? What mods do you currently have installed?

Generally this can happen because two or mods mods conflict with each other. But, I'll need more information to help you.

**Comment by DragonsMage1** [comment]
![20220910105208_1](https://user-images.githubusercontent.com/107729417/189488854-758cd612-ddc8-45c4-9370-964bb9dc7092.jpg)
This is the game log after I try to open a chest and nothing happens,
also I don't have any mods installed except for the required dependencies.

**Comment by JustDerb** [comment]
Looks like problems loading `UnityEngine.Networking` (`FileNotFoundException`)

- Did you install the mod via the Mod Manager, or manually? I cannot help/support manual installs.
- Do you have any other mods installed? Try disabling all but VsTwitch (and it's dependencies)

**Comment by DragonsMage1** [comment]
I had installed it using the mod manager and I don’t have any other mods installed except for the mod itself and the dependencies

**Comment by JustDerb** [comment]
Thanks for the info. I'm curious: if you play the game again with this configuration do you receive the same error messages? It's been a while since this issue was created and a while before I am triaging it (sorry about that).

**Comment by JustDerb** [comment]
Closing for staleness; please re-open if you see this issue again!
