### ISSUE TITLE
Multishop Terminal

### ISSUE THREAD

**Issue by RoY7x** [JustDerb/RoR2-VsTwitch#51]
I was wondering if under the behavior for the rivals stuff if it really makes sense with multishop terminals? Perhaps have it a toggle where it randomizes like a normal chest, or if it can turn off similarly to how you have it for the lunar buds?

**Comment by JustDerb** [comment]
I'm not sure I'm following you. What do you mean by "rivals stuff"?

The multishop behavior is similar to the regular chest, except you at least see what three items will be voted on by Twitch Chat.

**Comment by RoY7x** [comment]
> I'm not sure I'm following you. What do you mean by "rivals stuff"?
> 
> The multishop behavior is similar to the regular chest, except you at least see what three items will be voted on by Twitch Chat.

I'm mainly saying it makes less sense to vote on it since everything is visible on a multishop terminal then a chest. Unless it's one of the slots that holds a random item? I was just mainly asking if there would be the possibility of a toggle switch to turn that feature off, similarly to how you currently have an option for the lunar items. Or maybe to have item voting only for the random item slot on those types of shops though that sounds like it would be a fair bit more complex to make happen.

**Comment by JustDerb** [comment]
So the random item is implemented in the game as "hidden" - when the level starts all items are rolled and placed in chests/multishops. The "random" icon is another roll that simply changes the displayed icon. The multishop behavior of this mod was specifically chosen to allow streamers to have some influence on the "randomness" that this mod brings. The hope is that you can easily see what 3 items chat can choose from and have some dialog to try to influence chat into what item to actually pick. This also plays nicely with the fact that you get 3 choices, and multishops have 3 slots too.

**Comment by RoY7x** [comment]
Ahhh, I did not know it was already a preset item that just had an icon swap to appear as though it was random. Clever from the devs, but I can definitely see why now what I'm asking would be a massive challenge. Thank you for the replies!
