### ISSUE TITLE
No Config File? (Risk Of Options hard dep)

### ISSUE THREAD

**Issue by meburningslime** [JustDerb/RoR2-VsTwitch#60]
Hello,
I am fairly new to advanced modding, so bear with me if I am making an obvious mistake. I opened the game several times on multiple accounts through the modded Thunderstore client, yet when I go to the Config section of Thunderstore, there is nothing except the other modpack's files. I have launched it multiple times and there are no other mods except for the required dependencies. Thank you for any and all help.

**Comment by JustDerb** [comment]
To be clear, do you not see this entry after launching the game (via "Start modded") in the "Config editor" section?

![image](https://github.com/JustDerb/RoR2-VsTwitch/assets/1020220/7205187d-0378-4c73-9e4f-010d03ab5cfa)

Can you comment your "profile as a code" via Settings > "Export profile as code"? This will allow me to double check you have the mod installed. To help troubleshooting further.

![image](https://github.com/JustDerb/RoR2-VsTwitch/assets/1020220/e79d0db7-98b6-4e4c-a48f-52e9a1ff1d24)

**Comment by meburningslime** [comment]
![image](https://github.com/JustDerb/RoR2-VsTwitch/assets/109699325/282508a8-54a3-4f9a-90f1-580f4b8b0455)

0190238b-51e1-83d9-063e-297bee629ba8

Here you go, this was my second profile in which I attempted to get this fixed. Thank you so much for the swift response, I greatly appreciate your help.

**Comment by JustDerb** [comment]
Hmm... can you install https://thunderstore.io/package/Rune580/Risk_Of_Options/ as well? I'm wondering if the mod somehow has a hard dependency on it now (it shouldn't).

If you see any red text (errors) in the console after booting the game modded, please send that to me as well! (If you see something in red about VSTwitch then there might be a bug.

**Comment by JustDerb** [comment]
I see I can repro. I see this in the console:

```
[Error  :   BepInEx] Could not load [VsTwitch 1.0.14] because it has missing dependencies: com.rune580.riskofoptions
```

So it looks like I somehow made it as a hard dependency :( I'll fix it in the next release. For now, downloading the "Risk_Of_Options" mod in the mod manager will fix this.

**Comment by JustDerb** [comment]
I've pushed out a new update (1.0.15) that fixes this. So the Risk Of Options mod is _actually_ optional.

**Comment by meburningslime** [comment]
Thank you so very much! This will greatly help me, the mod is finally working as intended. Many blessings!
